/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    aws_project_region: "us-east-2",
    aws_cognito_identity_pool_id: "us-east-2:79f95687-153e-40c1-96b5-d93be2fa6bc0",
    aws_cognito_region: "us-east-2",
    aws_user_pools_id: "us-east-2_sIezNghVw",
    aws_user_pools_web_client_id: "5hvg1trg74hl6q74853g6hn0k4",
    oauth: {},
    aws_cognito_login_mechanism: ["EMAIL"],
    aws_cognito_signup_attributes: ["EMAIL"],
    aws_cognito_mfa_configuration: "OFF",
    aws_cognito_mfa_types: ["SMS"],
    aws_cognito_password_protection_settings: {
        passwordPolicyMinLength: 8,
        passwordPolicyCharacters: []
    },
    aws_appsync_graphqlEndpoint:
        "https://pjx2zj4ucnhtbi6kqydee5hhxi.appsync-api.us-east-2.amazonaws.com/graphql",
    aws_appsync_region: "us-east-2",
    aws_appsync_authenticationType: "AMAZON_COGNITO_USER_POOLS"
};

export default awsmobile;
