export { default as Home } from "./home/home";
export { default as SinglePlayerGame } from "./single-player/single-player";
export { default as Settings } from "./settings/settings";
export { default as Login } from "./login/login";
export { default as Signup } from "./signup/Signup";
export { default as ChangePassword } from "./change-password/changePassword";
export { default as ForgotPassword } from "./forgot_password/forgotPassword";
export { default as MultiPlayerHome } from "./multiPlayer-home/multiPlayer-home";
export { default as MultiPlayerGame } from "./multiplayer-game/MultiPlayerGame";
